project_id = "gtjhpkakousmdrzjpdat"

[api]
port = 54321
external_url = "http://localhost:54321"

[db]
port = 54322
shadow_port = 54320

[functions.create-user-admin]
verify_jwt = false

[functions.activate-pharmacy-plan]
verify_jwt = false

[functions.provision-merchant-access]
verify_jwt = false

[functions.delete-user-admin]
verify_jwt = false

[functions.create-staff-user]
verify_jwt = false

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://*"]
jwt_expiry = 3600
enable_signup = true

[storage]
enabled = true

[realtime]
enabled = true
